version: 0
allowPullRequests: public
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    extra:
      github:
        env: true
        events:
          - push
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
    payload:
      maxRunTime: 3600
      image: "node:10"
      env:
        NO_TEST_SKIP: "true"
      features:
        taskclusterProxy: true
      command:
        - "/bin/bash"
        - "--login"
        - "-c"
        - "git clone {{event.head.repo.url}} repo && cd repo && git checkout {{event.head.sha}} && yarn install && yarn test"
    metadata:
      name: "TaskCluster Built-In-Workers Tests"
      description: "All non-integration tests"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

