defaults:
  app:
    publishMetaData: !env:bool PUBLISH_METADATA

  # TaskCluster credentials
  taskcluster:
    rootUrl: !env TASKCLUSTER_ROOT_URL
    queue: none
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env TASKCLUSTER_ACCESS_TOKEN

  monitoring:
    enable: !env:bool MONITORING_ENABLE

  worker:
    workerId: "fail"
    workerType: "fail"
    workerGroup: "garbage-hybrid1999"
    provisionerId: "garbage-hybrid1999"
    queue: 

test:
  app:
    publishMetaData: false

  monitoring:
    enable: false
